
pipeline{
    agent any
	
    parameters{
	string(defaultValue:"TEST", description: "which env to deploy in?", name: "deployEnv")
    }

    stages{
	
	stage("Demo"){
	   steps{
              echo "string is set to: ${params.deployEnv}"
	   }
	}
    }
}