
pipeline{
    agent any
	
    parameters{
	booleanParam(defaultValue:false, description: "which env to deploy in?", name: "deployEnv")
    }

    stages{
	
	stage("Demo"){
	   steps{
	   
			script{
				if(params.deployEnv == false) {
					currentBuild.result == "SUCCESS"
					return
				
				}
				else {
					echo "booeanParam is set to : TRUE"
				}
				
			
			}
              
  }
	}
    }
}

